server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: car-service-route
              uri: http://localhost:8081
              predicates:
                - Path=/api/cars/**
            - id: booking-service-route
              uri: http://localhost:8082
              predicates:
                - Path=/api/auth/**, /api/bookings/**
